import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import {
  chainColors,
  colorPrimitives,
  darkColorSemantics,
  systemColors,
  type ColorReference
} from '../resources/style/tokens/colors'

export const generatedColorTokensPath = path.resolve(
  __dirname,
  '../resources/style/tokens/colors.generated.css'
)

function cssReference(reference: ColorReference) {
  if (typeof reference === 'string') return `var(--color-${reference})`

  return `color-mix(in srgb, var(--color-${reference.color}) ${reference.alpha * 100}%, transparent)`
}

export function generateColorTokensCss() {
  const lines = [
    '/* This file is generated by scripts/generate-color-tokens.ts. Do not edit directly. */',
    ':root {',
    ...Object.entries(colorPrimitives).map(([name, value]) => `  --color-${name}: ${value};`),
    '',
    ...Object.entries(systemColors).map(([name, value]) => `  --color-system-${name}: ${value};`),
    '',
    ...Object.entries(chainColors).map(([name, value]) => `  --color-chain-${name}: ${value};`),
    '}',
    '',
    ':root, .dark {',
    ...Object.entries(darkColorSemantics).map(
      ([name, reference]) => `  --color-${name}: ${cssReference(reference)};`
    ),
    '}',
    ''
  ]

  return lines.join('\n')
}

async function main() {
  const expected = generateColorTokensCss()
  const check = process.argv.includes('--check')

  if (check) {
    const actual = await readFile(generatedColorTokensPath, 'utf8').catch(() => '')
    if (actual !== expected) {
      console.error('Generated color tokens are stale. Run `bun run tokens:generate`.')
      process.exit(1)
    }
    return
  }

  await writeFile(generatedColorTokensPath, expected)
}

if (require.main === module) {
  main().catch((err) => {
    console.error(err)
    process.exit(1)
  })
}
