import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

import {
  colorPrimitives,
  darkColorSemantics,
  systemColors,
  type ColorReference
} from '../src/tokens/colors.ts'
import { borderTokens } from '../src/tokens/borders.ts'
import { elevationTokens } from '../src/tokens/elevation.ts'
import { layerTokens } from '../src/tokens/layers.ts'
import { motionTokens } from '../src/tokens/motion.ts'
import { opacityTokens } from '../src/tokens/opacity.ts'
import { radiusTokens } from '../src/tokens/radius.ts'
import { sizingTokens } from '../src/tokens/sizing.ts'
import { spacingTokens } from '../src/tokens/spacing.ts'
import { typographyTokens } from '../src/tokens/typography.ts'

export const generatedTokensPath = path.resolve(import.meta.dirname, '../src/tokens/tokens.generated.css')

function cssReference(reference: ColorReference) {
  if (typeof reference === 'string') return `var(--color-${reference})`

  return `color-mix(in srgb, var(--color-${reference.color}) ${reference.alpha * 100}%, transparent)`
}

function variables(values: Record<string, string>, prefix = '') {
  return Object.entries(values).map(([name, value]) => `  --${prefix}${name}: ${value};`)
}

export function generateTokensCss() {
  return [
    '/* Generated by packages/ui/scripts/generate-tokens.ts. Do not edit. */',
    ':root,',
    '.nf-root {',
    ...variables(colorPrimitives, 'color-'),
    '',
    ...variables(systemColors, 'color-system-'),
    '',
    ...Object.entries(darkColorSemantics).map(
      ([name, reference]) => `  --color-${name}: ${cssReference(reference)};`
    ),
    '',
    ...variables(spacingTokens),
    ...variables(typographyTokens),
    ...variables(radiusTokens),
    ...variables(borderTokens),
    ...variables(elevationTokens),
    ...variables(motionTokens),
    ...variables(opacityTokens),
    ...variables(sizingTokens),
    ...variables(layerTokens),
    '}',
    ''
  ].join('\n')
}

export async function generateTokens({ check = false } = {}) {
  const expected = generateTokensCss()
  if (check) {
    const actual = await readFile(generatedTokensPath, 'utf8').catch(() => '')
    if (actual !== expected) throw new Error('Generated UI tokens are stale. Run `bun run tokens:generate`.')
    return
  }
  await writeFile(generatedTokensPath, expected)
}

if (path.resolve(process.argv[1] || '') === path.resolve(import.meta.filename)) {
  await generateTokens({ check: process.argv.includes('--check') })
}
