import type { BunPlugin } from 'bun'
import { Buffer } from 'node:buffer'
import { cpSync, mkdirSync, rmSync, watch } from 'node:fs'
import path from 'node:path'

const root = import.meta.dir
const dist = path.join(root, 'dist')
const repoRoot = path.resolve(root, '../..')
const brandAssets = path.join(repoRoot, 'assets/brand/newframe')
const statusAssets = path.join(brandAssets, 'status')
const eip6963Icon = path.join(brandAssets, 'app-icon.png')

const watchMode = process.argv.includes('--watch')
const dev = watchMode || process.argv.includes('--dev')

// matches terser keep_classnames/keep_fnames from the old webpack config:
// minify whitespace and syntax but never mangle identifiers
const minify = dev ? false : { whitespace: true, syntax: true, identifiers: false }

// Bun maps `require('events')` to its node:events polyfill, an ESM module
// whose CJS-interop value is a namespace object — `class X extends EventEmitter`
// then throws "The superclass is not a constructor" at service-worker startup.
// Force the npm `events` package (a CJS class export) instead.
const eventsAlias: BunPlugin = {
  name: 'events-npm-alias',
  setup(build) {
    const eventsPath = Bun.resolveSync('events/events.js', root)
    build.onResolve({ filter: /^events$/ }, () => ({ path: eventsPath }))
  }
}

const entries = [
  { entry: 'src/newframe.ts', out: 'newframe' },
  { entry: 'src/settings/index.tsx', out: 'settings' },
  { entry: 'src/index.ts', out: 'index' }
]

const statusIconCopies: Record<string, string> = {
  'icon16.png': 'default-16.png',
  'icon48.png': 'default-48.png',
  'icon96.png': 'default-96.png',
  'icon96good.png': 'good-96.png',
  'icon96moon.png': 'moon-100.png'
}

async function imageDataUri(filePath: string, mimeType: string) {
  const bytes = await Bun.file(filePath).bytes()
  return `data:${mimeType};base64,${Buffer.from(bytes).toString('base64')}`
}

// inject.js — content script that bridges page <-> extension (was generated by src/inline.js)
const inject = `
  try {
    // sandboxed iframes have an opaque origin ("null") — postMessage with it throws,
    // and a throwing listener surfaces as a cryptic rejection on the sender side
    const pageOrigin = window.location.origin === 'null' ? '*' : window.location.origin
    chrome.runtime.onMessage.addListener((payload, sender, sendResponse) => {
      try {
        if (payload.type === 'eth:payload') {
          delete payload.type
          window.postMessage({type: 'eth:payload', payload: payload}, pageOrigin)
        }
        if (payload.type === 'embedded:action') {
          window.postMessage({type: 'embedded:action', action: payload.action}, pageOrigin)
        }
        if (payload.type === 'eth:event') {
          const { event, args } = payload
          delete payload.type
          window.postMessage({ type: 'eth:event', event, args }, pageOrigin)
        }
      } catch (e) {}
    })
    window.addEventListener('message', event => {
      if (event.source === window && event.data && event.data.type === 'eth:send') {
        try {
          chrome.runtime.sendMessage(event.data.payload)
        } catch (e) {
          // this content script generation was orphaned by an extension reload;
          // a fresh one re-registers via the background onInstalled re-injection
        }
      }
    })
    // newframe.js (page-world provider) survives extension reloads; inject once per page
    if (!document.documentElement.hasAttribute('data-newframe-provider')) {
      document.documentElement.setAttribute('data-newframe-provider', '1')
      let script = document.createElement('script')
      script.setAttribute('type', 'text/javascript')
      script.src = chrome.runtime.getURL('newframe.js')
      script.onload = function () { script.parentNode.removeChild(script) }
      const topLevel = document.head || document.documentElement
      topLevel.appendChild(script)
    }
  } catch (e) {
    console.log(e)
  }
`

async function build(): Promise<boolean> {
  let ok = true
  const eip6963IconDataUri = await imageDataUri(eip6963Icon, 'image/png')

  for (const { entry, out } of entries) {
    const result = await Bun.build({
      entrypoints: [path.join(root, entry)],
      outdir: dist,
      target: 'browser',
      format: 'iife',
      naming: `${out}.[ext]`,
      minify,
      plugins: [eventsAlias],
      define: {
        'process.env.NODE_ENV': dev ? '"development"' : '"production"',
        __NEWFRAME_EIP6963_ICON__: JSON.stringify(eip6963IconDataUri)
      }
    })

    if (!result.success) {
      ok = false
      console.error(`❌ ${entry} failed:`)
      for (const log of result.logs) console.error(log)
    } else {
      console.log(`✅ ${entry} -> dist/${out}.js`)
    }
  }

  await Bun.write(path.join(dist, 'inject.js'), inject)

  for (const file of ['manifest.json', 'settings.html']) {
    await Bun.write(path.join(dist, file), Bun.file(path.join(root, 'src', file)))
  }

  const iconsDist = path.join(dist, 'icons')
  mkdirSync(iconsDist, { recursive: true })
  for (const [file, source] of Object.entries(statusIconCopies)) {
    await Bun.write(path.join(iconsDist, file), Bun.file(path.join(statusAssets, source)))
  }

  cpSync(path.join(root, 'src/style'), path.join(dist, 'style'), { recursive: true })

  return ok
}

rmSync(dist, { recursive: true, force: true })
const ok = await build()

if (watchMode) {
  console.log('👀 Watching src/ and assets/ for changes...')
  // fs.watch on macOS re-fires for events caused by the build itself,
  // so ignore anything that arrives while building or right after
  let building = false
  let quietUntil = 0
  let pending: ReturnType<typeof setTimeout> | null = null
  for (const watchRoot of [path.join(root, 'src'), brandAssets]) {
    watch(watchRoot, { recursive: true }, () => {
      if (building || Date.now() < quietUntil) return
      if (pending) clearTimeout(pending)
      pending = setTimeout(async () => {
        building = true
        console.log('🔁 Rebuilding...')
        await build()
        quietUntil = Date.now() + 1000
        building = false
      }, 100)
    })
  }
} else if (!ok) {
  process.exit(1)
} else {
  console.log(
    '✅ Extension built to dist/ (load in Chrome via chrome://extensions or Firefox via about:debugging)'
  )
}
