import { NATIVE_CURRENCY } from '../../constants'

export const FLASH_ANVIL_CHAIN_ID = 31337
export const FLASH_BASE_CHAIN_ID = 8453

export const FLASH_NATIVE_ETH_TOKEN_ADDRESS = NATIVE_CURRENCY
export const FLASH_WETH_ADDRESS = '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
export const FLASH_USDC_ADDRESS = '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48'
export const FLASH_BASE_WETH_ADDRESS = '0x4200000000000000000000000000000000000006'
export const FLASH_BASE_USDC_ADDRESS = '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913'

export const FLASH_NATIVE_ETH_ASSET_SYMBOL = 'ETH'
export const FLASH_WETH_ASSET_SYMBOL = 'WETH'
export const FLASH_USDC_ASSET_SYMBOL = 'USDC'

export const FLASH_MARKET_ORDER_TYPE = 'market'
export const FLASH_LIMIT_ORDER_TYPE = 'limit'
export const FLASH_TWAP_ORDER_TYPE = 'twap'
export const FLASH_STOP_ORDER_TYPE = 'stop'
export const FLASH_STOP_LOSS_ORDER_TYPE = 'stop-loss'
export const FLASH_TAKE_PROFIT_ORDER_TYPE = 'take-profit'
export const FLASH_BRACKET_ORDER_TYPE = 'bracket'

export const FLASH_ORDER_TYPES = [
  FLASH_MARKET_ORDER_TYPE,
  FLASH_LIMIT_ORDER_TYPE,
  FLASH_TWAP_ORDER_TYPE,
  FLASH_STOP_ORDER_TYPE,
  FLASH_STOP_LOSS_ORDER_TYPE,
  FLASH_TAKE_PROFIT_ORDER_TYPE,
  FLASH_BRACKET_ORDER_TYPE
] as const

export const FLASH_TRADE_SIDES = ['buy', 'sell'] as const
